name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest, flags: -GNinja }
        #- { name: Windows, os: windows-latest }
        #- { name: MacOS,   os: macos-latest }
    steps:
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@v1
      with:
        version: sdl3-latest
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install dev libx11-dev
    - name: Get fte sources
      uses: actions/checkout@v2
    - name: Build
      working-directory: ./src
      run: make -f fte-unix.mak cfte xfte sdlfte -j`nproc`
